domain:          'https://tenfoldpath.com'
icon_url:        'apple-touch-icon.png'

highligher: null
base_url: ''
permalink: /codex/:title/

incremental: true

plugins:
  - jekyll-feed

defaults:
  -
    scope:
      path: "/codex"
      type: "posts"
    values:
      layout: "page"

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
