analytics_token: 'UA-28083204-4'
gravatar_hash: 'aa6461def0e558a9d8b0e20479119b38'

pygments: false
permalink: /:categories/:title/

markdown: rdiscount
rdiscount:
  extensions:
    - autolink
    - footnotes
    - smart

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - TODO.md
