domain:          'http://dan.brubakerhorst.com'
analytics_token: 'UA-28083204-4'
gravatar_hash:   '5fc42f1f51ffe472c27edc9c320840fc'
icon_url:        'apple-touch-icon-precomposed.png'

highligher: null
base_url: ''
permalink: /:categories/:title/

markdown: rdiscount
rdiscount:
  extensions:
    - autolink
    - footnotes
    - smart

tag_page_layout: tag_page
tag_page_dir: blog/tags

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - TODO.md
