domain:          'http://dan.brubakerhorst.com'
icon_url:        'apple-touch-icon.png'

highligher: null
base_url: ''
permalink: /:title/

incremental: true

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - TODO.md
