server:          true
auto:            true
server_port:     4000
analytics_token: 'UA-28083204-4'

markdown: rdiscount
rdiscount:
  extensions: [smart]

pygments:    false
permalink:   /:categories/:title/

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
